version: 2
project_name: wagyu-script
builds:
  - id: default
    main: ./cmd/wagyu-script
    goos:
      - linux
      - windows
    goarch:
      - amd64
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - wagyu-script
nfpms:
  - id: default
    formats:
      - deb
      - rpm
      - exe
    maintainer: "@kurogee"
    description: "Wagyu Script"
    license: MIT
    vendor: "Your Company"
    homepage: "https://example.com"
    bindir: /usr/local/bin
    contents:
      - src: wagyu-script
        dst: /usr/local/bin/wagyu-script